// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfWdJY3Fw8jWhW9nnKyhjf6hZZPOdigng',
    appId: '1:814305692885:web:43aaa61d8290e5d1a5e65c',
    messagingSenderId: '814305692885',
    projectId: 'my-todo-app-68a4d',
    authDomain: 'my-todo-app-68a4d.firebaseapp.com',
    storageBucket: 'my-todo-app-68a4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2rQRFZTC7y5gD-HWAHXv_H6f34eEJJHA',
    appId: '1:814305692885:android:01d8f138e1cc7567a5e65c',
    messagingSenderId: '814305692885',
    projectId: 'my-todo-app-68a4d',
    storageBucket: 'my-todo-app-68a4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD746IGjtf5-hl-T9sT0tItC3pWl9bE7fU',
    appId: '1:814305692885:ios:45467ded65b868d4a5e65c',
    messagingSenderId: '814305692885',
    projectId: 'my-todo-app-68a4d',
    storageBucket: 'my-todo-app-68a4d.appspot.com',
    iosBundleId: 'com.example.ftest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD746IGjtf5-hl-T9sT0tItC3pWl9bE7fU',
    appId: '1:814305692885:ios:fde1fef78d22a8d7a5e65c',
    messagingSenderId: '814305692885',
    projectId: 'my-todo-app-68a4d',
    storageBucket: 'my-todo-app-68a4d.appspot.com',
    iosBundleId: 'com.example.ftest.RunnerTests',
  );
}
